In [2]:
import pandas as pd
import numpy as np

# TASK-1

In [3]:
S1 = pd.Series(np.random.rand(4))
S2 = pd.Series(np.random.rand(4))
S3 = pd.Series(np.random.rand(4))
S4 = pd.Series(np.random.rand(4))

In [6]:
data = pd.DataFrame([S1,S2,S3,S4])
data

          0         1         2         3
0  0.162368  0.722656  0.161640  0.576681
1  0.159927  0.584770  0.603140  0.469220
2  0.541759  0.073782  0.028369  0.222581
3  0.505001  0.018655  0.143987  0.021804

# TASK - 2

In [7]:
data.columns = ['Random value 1','Random value 2','Random value 3','Random value 4']
data

   Random value 1  Random value 2  Random value 3  Random value 4
0        0.162368        0.722656        0.161640        0.576681
1        0.159927        0.584770        0.603140        0.469220
2        0.541759        0.073782        0.028369        0.222581
3        0.505001        0.018655        0.143987        0.021804

# TASK - 3

In [8]:
data.describe()

       Random value 1  Random value 2  Random value 3  Random value 4
count        4.000000        4.000000        4.000000        4.000000
mean         0.342264        0.349965        0.234284        0.322571
std          0.209675        0.355938        0.252908        0.249357
min          0.159927        0.018655        0.028369        0.021804
25%          0.161758        0.060000        0.115083        0.172387
50%          0.333685        0.329276        0.152814        0.345900
75%          0.514191        0.619241        0.272015        0.496085
max          0.541759        0.722656        0.603140        0.576681

# TASK - 4

In [ ]:
data.isnull()

   Random value 1  Random value 2  Random value 3  Random value 4
0           False           False           False           False
1           False           False           False           False
2           False           False           False           False
3           False           False           False           False

In [ ]:
data.isnull().sum()

Random value 1    0
Random value 2    0
Random value 3    0
Random value 4    0
dtype: int64

In [12]:
data.iloc[0,3] = np.nan
data.iloc[2,2] = np.nan

In [13]:
data

   Random value 1  Random value 2  Random value 3  Random value 4
0        0.162368        0.722656        0.161640             NaN
1        0.159927        0.584770        0.603140        0.469220
2        0.541759        0.073782             NaN             NaN
3        0.505001        0.018655        0.143987        0.021804

In [14]:
data.isnull()

   Random value 1  Random value 2  Random value 3  Random value 4
0           False           False           False            True
1           False           False           False           False
2           False           False            True            True
3           False           False           False           False

In [15]:
data.isnull().sum()

Random value 1    0
Random value 2    0
Random value 3    1
Random value 4    2
dtype: int64

In [16]:
data['Random value 1'].dtype

dtype('float64')

In [18]:
data['Random value 2'].dtype

dtype('float64')

In [17]:
data['Random value 3'].dtype

dtype('float64')

In [19]:
data['Random value 4'].dtype

dtype('float64')

# TASK - 5

In [20]:
data.loc[0:,'Random value 2':'Random value 3']

   Random value 2  Random value 3
0        0.722656        0.161640
1        0.584770        0.603140
2        0.073782             NaN
3        0.018655        0.143987

In [ ]:
data.iloc[0:,1:3]

   Random value 2  Random value 3
0        0.530027             NaN
1        0.538733        0.432435
2             NaN        0.780319
3        0.661269        0.501653